language: node_js
node_js:
  - '12'

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn

script:
  - yarn format

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email:
    on_failure: change
